### PR TITLE
Major camera-streamer WebRTC updates!

### PR DESCRIPTION
**Pull request by QuinnDamerell**
I have been working with the developer behind `camera-streamer` to update the WebRTC logic to support faster video streaming times (with trickle ICE), more reliable WebRTC streaming (fixing race conditions with video stream starting), and adding full WebRTC protocol with (optional) ICE server support. After 4 weeks of work, the changes have been tested and released in v0.2.2!

This change does two things:
1. The new default branch of `camera-streamer` is `main`, not `master`.
2. At the request of the `camera-streamer` dev, I have changed the logic to target a tag version of camera-streamer, so each user installing crowsnest doesn't pull whatever is on the head of main.

### CODE REVIEW

**Comment by QuinnDamerell** [comment]
I'm aware there's currently no way to update `camera-streamer` after the initial crowsnest install, which is why we have been trying to get the changes done ASAP!

**Comment by QuinnDamerell** [comment]
One last thing, the current Mainsail WebRTC implementation will still work, but I will also be putting out a PR for Mainsail soon to update the logic to use the new features, such as trickle ICE, which makes the WebRTC camera connection faster.

**Comment by meteyou** [comment]
As I know, there will be a change to install deb packages instead of the "self-compile" version of camera-streamer. We have to wait for an answer from @KwadFan about this.

**Comment by QuinnDamerell** [comment]
@meteyou yup, I didn't realize they were working on that now, I know they are both busy and will be unavailable for a while shortly. I whipped this up quickly to take some work off them, but it sounds like they want to do the binary version now, which is great!

**Pull request closed without merging**
